const recipes = [
  {
    id: 1,
    name: '红烧肉',
    description: '肥而不腻，入口即化的经典红烧肉',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/h.jpg',
    time: '90分钟',
    servings: '4人份',
    difficulty: '中等',
    tags: ['经典', '下饭'],
    category: 'meat',
    ingredients: ['五花肉500克', '姜片5片', '葱段10克', '八角2个', '桂皮1小块', '生抽2勺', '老抽1勺', '冰糖30克', '料酒2勺'],
    steps: [
      { text: '五花肉切成块，锅底放入一点点油，把五花肉放入锅里煸出油脂，油腥气很重需要扔掉', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/h1.jpg' },
      { text: '锅中放少许油，加入冰糖炒出糖色', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/h2.jpg' },
      { text: '加入葱姜八角桂皮炒香,放入五花肉翻炒上色,倒入料酒、生抽、老抽翻炒均匀', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/h3.jpg' },
      { text: '加入开水没过肉，大火烧开转小火炖60分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/h4.jpg' },
      { text: '大火收汁即可出锅', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/h5.jpg' }
    ],
    notes: '炒糖色时火候要小，避免糊锅。炖肉时一定要用开水，这样肉质才不会柴。'
  },
  {
    id: 2,
    name: '宫保鸡丁',
    description: '酸甜微辣，花生酥脆的经典川菜',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/g.jpg',
    time: '30分钟',
    servings: '3人份',
    difficulty: '中等',
    tags: ['川菜', '下饭'],
    category: 'meat',
    ingredients: ['鸡胸肉300克', '花生米100克', '干辣椒10个', '花椒1勺', '葱姜蒜适量', '生抽2勺', '醋2勺', '白糖2勺', '料酒1勺'],
    steps: [
      { text: '鸡胸肉切丁，加料酒、生抽、淀粉腌制15分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/g1.jpg' },
      { text: '花生米炸熟备用', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/g2.jpg' },
      { text: '调宫保汁：生抽、醋、白糖、淀粉、水混合', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/g3.jpg' },
      { text: '锅中放油，炒香花椒和干辣椒', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/g4.jpg' },
      { text: '加入鸡丁翻炒至变色', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/g5.jpg' },
      { text: '加入葱姜蒜翻炒', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/g6.jpg' },
      { text: '倒入宫保汁和花生米翻炒均匀', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/g7.jpg' }
    ],
    notes: '花生米最后放保持酥脆口感，花椒和辣椒炒出香味即可，不要炒糊。'
  },
  {
    id: 3,
    name: '鱼香肉丝',
    description: '咸甜酸辣，香气浓郁的川菜经典',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/y.jpg',
    time: '30分钟',
    servings: '3人份',
    difficulty: '中等',
    tags: ['川菜', '下饭'],
    category: 'meat',
    ingredients: ['猪肉丝300克', '胡萝卜1根', '木耳10朵', '青椒1个', '葱姜蒜适量', '豆瓣酱1勺', '生抽2勺', '醋2勺', '白糖2勺'],
    steps: [
      { text: '肉丝加料酒、生抽、淀粉腌制', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/y1.jpg' },
      { text: '胡萝卜、木耳、青椒切丝', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/y2.jpg' },
      { text: '调鱼香汁：生抽、醋、白糖、淀粉、水混合', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/y3.jpg' },
      { text: '肉丝翻炒至变色', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/y4.jpg' },
      { text: '锅中放油炒香豆瓣酱', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/y5.jpg' },
      { text: '加入葱姜蒜和蔬菜丝翻炒', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/y6.jpg' },
      { text: '倒入鱼香汁翻炒均匀', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/y7.jpg' }
    ],
    notes: '鱼香汁的比例很关键，糖醋比例约为1:1。豆瓣酱要炒出红油才香。'
  },
  {
    id: 4,
    name: '糖醋排骨',
    description: '酸甜可口，外酥里嫩的经典家常菜',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/t.jpg',
    time: '60分钟',
    servings: '4人份',
    difficulty: '中等',
    tags: ['经典', '酸甜'],
    category: 'meat',
    ingredients: ['排骨500克', '姜片5片', '葱段10克', '生抽2勺', '老抽1勺', '醋3勺', '白糖3勺', '料酒2勺'],
    steps: [
      { text: '排骨冷水下锅焯水，捞出沥干', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/t1.jpg' },
      { text: '锅中放油，加入白糖炒出糖色', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/t2.jpg' },
      { text: '放入排骨翻炒上色', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/t3.jpg' },
      { text: '加入葱姜炒香,倒入料酒、生抽、老抽翻炒', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/t4.jpg' },
      { text: '加入开水没过排骨，小火炖40分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/t5.jpg' },
      { text: '加入醋，大火收汁', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/t6.jpg' }
    ],
    notes: '醋要分两次加，炖的时候加一部分，收汁前加一部分，这样醋香更浓郁。'
  },
  {
    id: 5,
    name: '麻婆豆腐',
    description: '麻辣鲜香，豆腐嫩滑的川菜代表',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/m.jpg',
    time: '25分钟',
    servings: '3人份',
    difficulty: '简单',
    tags: ['川菜', '下饭'],
    category: 'vegetable',
    ingredients: ['嫩豆腐1块', '猪肉末100克', '豆瓣酱1勺', '花椒粉1勺', '葱姜蒜适量', '生抽1勺', '料酒1勺'],
    steps: [
      { text: '豆腐切成小块，开水焯烫去除豆腥味', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/m1.jpg' },
      { text: '加入葱姜蒜炒香', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/m2.jpg' },
      { text: '加入豆瓣酱炒出红油', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/m3.jpg' },
      { text: '锅中放油炒香猪肉末', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/m4.jpg' },
      { text: '加入开水，放入豆腐', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/m5.jpg' },
      { text: '炖煮一分钟后加入适量的盐', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/m6.jpg' },
      { text: '勾芡后撒花椒粉出锅', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/m7.jpg' }
    ],
    notes: '豆腐一定要用嫩豆腐，煮的时候不要频繁翻动以免碎掉。花椒粉最后撒，香气更浓。'
  },
  {
    id: 6,
    name: '蒜蓉西兰花',
    description: '清爽健康，营养丰富的家常菜',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/s.jpg',
    time: '15分钟',
    servings: '2人份',
    difficulty: '简单',
    tags: ['素菜', '健康'],
    category: 'vegetable',
    ingredients: ['西兰花1颗', '大蒜5瓣', '生抽1勺', '蚝油1勺', '盐适量'],
    steps: [
      { text: '西兰花切成小朵，洗净', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/s1.jpg' },
      { text: '锅中放油，爆香蒜末', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/s2.jpg' },
      { text: '放入西兰花翻炒，加入生抽和蚝油调味', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/s3.jpg' },
    ],
    notes: '西兰花焯水时间不宜过长，保持翠绿口感更好。蒜末不要炒糊，否则会发苦。'
  },
  {
    id: 7,
    name: '地三鲜',
    description: '东北经典，茄子土豆青椒的完美组合',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/d5.jpg',
    time: '40分钟',
    servings: '3人份',
    difficulty: '中等',
    tags: ['东北菜', '下饭'],
    category: 'vegetable',
    ingredients: ['茄子1根', '土豆1个', '青椒2个', '葱姜蒜适量', '酱油2勺', '蚝油1勺', '盐适量', '白糖', '淀粉'],
    steps: [
      { text: '茄子、土豆、青椒切块', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/d1.jpg' },
      { text: '土豆炸至金黄捞出', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/d2.jpg' },
      { text: '茄子炸至变软捞出', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/d3.jpg' },
      { text: '	将两勺酱油 一勺蚝油 一勺淀粉 半勺c 一茶勺盐 五勺清水调成汁', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/d4.jpg' },
      { text: '锅中留底油，爆香葱姜蒜，加入所有食材翻炒', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/d5.jpg' },
    ],
    notes: '茄子切好后可以撒点盐腌一下，炸的时候吸油更少。炸土豆时油温要高，才能外酥里嫩。'
  },
  {
    id: 8,
    name: '清炒时蔬',
    description: '简单快手，保留蔬菜原味的健康菜',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/q.jpg',
    time: '10分钟',
    servings: '2人份',
    difficulty: '简单',
    tags: ['素菜', '健康'],
    category: 'vegetable',
    ingredients: ['青菜/菠菜/油麦菜200克', '大蒜3瓣', '盐适量', '香油少许'],
    steps: [
      { text: '蔬菜洗净，大蒜切末', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/q1.jpg' },
      { text: '锅中放油，爆香蒜末', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/q2.jpg' },
      { text: '放入蔬菜翻炒，加入盐调味，翻炒至蔬菜变软，滴几滴香油出锅', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/q3.jpg' },
    ],
    notes: '绿叶蔬菜要大火快炒，时间不宜过长，否则营养流失且口感变差。'
  },
  {
    id: 9,
    name: '清蒸鱼',
    description: '鲜嫩多汁，原汁原味的海鲜美味',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/qz.jpg',
    time: '20分钟',
    servings: '3人份',
    difficulty: '简单',
    tags: ['海鲜', '清淡'],
    category: 'seafood',
    ingredients: ['鲈鱼/草鱼1条', '姜片5片', '葱段适量', '蒸鱼豉油3勺', '料酒1勺', '食用油适量'],
    steps: [
      { text: '鱼处理干净，在鱼身上划几刀，用料酒涂抹鱼身腌制10分钟，盘中铺姜片和葱段，放上鱼', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/qz1.jpg' },
      { text: '蒸锅水开后放入鱼，大火蒸8-10分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/qz2.jpg' },
      { text: '取出倒掉蒸出的水，去掉葱姜，铺上新鲜葱姜丝，淋上蒸鱼豉油，浇上热油激发出香味', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/qz3.jpg' },
    ],
    notes: '蒸鱼时间根据鱼的大小调整，蒸好后一定要倒掉腥水。热油一定要滚烫，才能激发出葱姜的香味。'
  },
  {
    id: 10,
    name: '红烧鱼',
    description: '色泽红亮，味道醇厚的家常鱼',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hs.jpg',
    time: '35分钟',
    servings: '3人份',
    difficulty: '中等',
    tags: ['海鲜', '下饭'],
    category: 'seafood',
    ingredients: ['鲤鱼/草鱼1条', '姜片5片', '葱段适量', '八角2个', '生抽2勺', '老抽1勺', '白糖2勺', '料酒2勺'],
    steps: [
      { text: '鱼处理干净，擦干水分，两面拍淀粉', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hs1.jpg' },
      { text: '锅中放油，将鱼煎至两面金黄', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hs2.jpg' },
      { text: '油锅中放入姜丝、葱花爆香，放入小米椒块炒匀，淋入料酒、生抽炒香，加盐调味，放入鲫鱼，加入适量清水，盖上盖，小火焖煮 15分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hs3.jpg' },
      { text: '大火收汁即可', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hs4.jpg' }
    ],
    notes: '煎鱼时油温要高，先不要翻动，等一面定型后再翻面。加水一定要用开水。'
  },
  {
    id: 11,
    name: '蒜蓉粉丝蒸扇贝',
    description: '鲜嫩爽滑，蒜香浓郁的海鲜佳肴',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sb.jpg',
    time: '20分钟',
    servings: '3人份',
    difficulty: '简单',
    tags: ['海鲜', '鲜美'],
    category: 'seafood',
    ingredients: ['扇贝6个', '粉丝1把', '大蒜10瓣', '生抽2勺', '蚝油1勺', '葱花适量'],
    steps: [
      { text: '扇贝洗净，粉丝泡软,大蒜切末，', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sb1.jpg' },
      { text: '生蒜和炸蒜混合，加入生抽蚝油拌匀', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sb2.jpg' },
      { text: '粉丝铺在扇贝底部', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sb3.jpg' },
      { text: '蒸锅水开后蒸5分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sb4.jpg' },
      { text: '撒上葱花，淋上热油', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sb5.jpg' }
    ],
    notes: '蒜蓉分两半，一半炸香一半生蒜，这样味道更丰富。蒸的时间不要太长，否则扇贝肉会变老。'
  },
  {
    id: 12,
    name: '酸菜鱼',
    description: '酸香开胃，鱼肉嫩滑的川菜经典',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sc.jpg',
    time: '45分钟',
    servings: '4人份',
    difficulty: '中等',
    tags: ['川菜', '汤菜'],
    category: 'seafood',
    ingredients: ['草鱼1条', '酸菜200克', '泡椒10个', '姜片5片', '蒜末适量', '花椒1勺', '料酒2勺', '蛋清1个', '淀粉适量'],
    steps: [
      { text: '鱼肉切片，加料酒、蛋清、淀粉腌制', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sc1.jpg' },
      { text: '锅中放油炒香酸菜和泡椒', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sc2.jpg' },
      { text: '加入开水煮10分钟，熬出汤味', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sc3.jpg' },
      { text: '滑入鱼片煮至变色即可', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sc4.jpg' }
    ],
    notes: '鱼片不要煮太久，变色即熟，否则会老。酸菜一定要炒香，汤才会浓郁。'
  },
  {
    id: 13,
    name: '番茄蛋汤',
    description: '酸甜可口，营养丰富的家常汤',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/fq4.jpg',
    time: '15分钟',
    servings: '2人份',
    difficulty: '简单',
    tags: ['汤羹', '家常'],
    category: 'soup',
    ingredients: ['番茄2个', '鸡蛋2个', '葱花适量', '盐适量', '香油少许'],
    steps: [
      { text: '番茄切块，鸡蛋打散', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/fq1.jpg' },
      { text: '锅中放油，炒软番茄,加入开水煮沸', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/fq2.jpg' },
      { text: '淋入蛋液，边倒边搅拌', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/fq3.jpg' },
      { text: '加入盐调味,撒上葱花，滴香油出锅', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/fq4.jpg' }
    ],
    notes: '番茄要炒出红油，汤才会浓郁。蛋液要缓慢倒入，边倒边搅拌，蛋花才会均匀。'
  },
  {
    id: 14,
    name: '酸辣汤',
    description: '酸辣开胃，暖身驱寒的经典汤品',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sl5.jpg',
    time: '20分钟',
    servings: '3人份',
    difficulty: '简单',
    tags: ['汤羹', '开胃'],
    category: 'soup',
    ingredients: ['豆腐1块', '木耳10朵', '鸡蛋1个', '火腿50克', '醋3勺', '胡椒粉1勺', '生抽1勺', '淀粉适量'],
    steps: [
      { text: '豆腐、木耳、火腿切丝', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sl1.jpg' },
      { text: '锅中水烧开，加入食材煮5分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sl2.jpg' },
      { text: '加入生抽调味,淋入水淀粉勾芡', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sl3.jpg' },
      { text: '淋入蛋液搅拌', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sl4.jpg' },
      { text: '搅拌均匀出锅', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sl5.jpg' }
    ],
    notes: '醋一定要最后放，这样醋香才不会挥发。胡椒粉要适量，太多会发苦。'
  },
  {
    id: 15,
    name: '排骨汤',
    description: '营养丰富，汤鲜味美的滋补汤',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/pg.jpg',
    time: '90分钟',
    servings: '4人份',
    difficulty: '中等',
    tags: ['汤羹', '滋补'],
    category: 'soup',
    ingredients: ['排骨500克', '猴头菇', '姜片5片', '葱段适量', '盐适量'],
    steps: [
      { text: '排骨冷水下锅焯水,捞出用清水洗净', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/pg1.jpg' },
      { text: '猴头菇提前2小时泡发。途中反复挤压~捏捏捏~', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/pg2.jpg' },
      { text: '所有食材放入砂锅,加入开水没过食材', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/pg3.jpg' },
      { text: '大火烧开转小火炖60分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/pg4.jpg' },
      { text: '最后加盐调味', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/pg5.jpg' }
    ],
    notes: '焯水一定要冷水下锅，这样血水才能充分排出。盐要最后放，这样肉质更嫩。'
  },
  {
    id: 16,
    name: '小米粥',
    description: '养胃健康，口感细腻的营养粥',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/xm.jpg',
    time: '40分钟',
    servings: '3人份',
    difficulty: '简单',
    tags: ['汤羹', '健康'],
    category: 'soup',
    ingredients: ['小米100克', '大米50克', '水适量', '红枣几颗'],
    steps: [
      { text: '小米和大米淘洗干净', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/xm1.jpg' },
      { text: '提前浸泡30分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/xm2.jpg' },
      { text: '放入锅中，加入适量水', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/xm3.jpg' },
      { text: '大火烧开', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/xm4.jpg' },
      { text: '转小火慢熬20分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/xm5.jpg' },
      { text: '加入红枣继续熬10分钟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/xm6.jpg' },
      { text: '搅拌均匀出锅', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/xm7.jpg' }
    ],
    notes: '小米提前浸泡更容易煮烂。熬煮时要不时搅拌，防止粘锅。'
  },
  {
    id: 17,
    name: '糖醋里脊',
    description: '外酥里嫩，酸甜可口的经典名菜',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/tclj4.jpg',
    time: '40分钟',
    servings: '3人份',
    difficulty: '中等',
    tags: ['经典', '酸甜'],
    category: 'meat',
    ingredients: ['猪里脊300克', '淀粉适量', '鸡蛋1个', '番茄酱3勺', '白糖2勺', '醋2勺', '生抽1勺'],
    steps: [
      { text: '猪里脊切条，加料酒、加鸡蛋和淀粉拌匀,盐腌制', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/tclj1.jpg' },
      { text: '锅中放油，中火炸里脊,复炸一次更酥脆', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/tclj2.jpg' },
      { text: '锅中留底油，加入番茄酱炒香', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/tclj3.jpg' },
      { text: '加入糖、醋、生抽和少许水,倒入里脊翻炒均匀', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/tclj4.jpg' },
    ],
    notes: '复炸可以让外皮更酥脆。酱汁要熬到浓稠才能挂在肉上。'
  },
  {
    id: 18,
    name: '回锅肉',
    description: '肥而不腻，香气扑鼻的川菜经典',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg.jpg',
    time: '30分钟',
    servings: '3人份',
    difficulty: '中等',
    tags: ['川菜', '下饭'],
    category: 'meat',
    ingredients: ['五花肉300克', '青蒜苗2根', '豆瓣酱1勺', '甜面酱1勺', '姜片5片', '料酒1勺'],
    steps: [
      { text: '五花肉冷水下锅煮熟', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg1.jpg' },
      { text: '捞出切片,青蒜苗切段', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg2.jpg' },
      { text: '锅烧热， 放入适量的油， 下入姜片和大蒜片爆香；爆香后加入郫县豆瓣酱一起煸炒；', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg3.jpg' },
      { text: '加入红辣椒和大蒜白；', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg4.jpg' },
      { text: '加入青蒜苗翻炒均匀', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg5.jpg' }
    ],
    notes: '五花肉一定要煮到八分熟，切片不要太薄。煸炒时要把油逼出来，这样才不腻。'
  },
  {
    id: 19,
    name: '可乐鸡翅',
    description: '甜香浓郁，色泽红亮的家常美味',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/kl.jpg',
    time: '40分钟',
    servings: '3人份',
    difficulty: '简单',
    tags: ['家常', '酸甜'],
    category: 'meat',
    ingredients: ['鸡翅8个', '可乐1罐', '姜片5片', '葱段适量', '生抽2勺', '老抽1勺', '料酒2勺'],
    steps: [
      { text: '鸡翅焯水，捞出沥干', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/kl1.jpg' },
      { text: '锅中放油，将鸡翅煎至两面金黄', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/kl2.jpg' },
      { text: '加入葱姜炒香', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/kl3.jpg' },
      { text: '倒入料酒、生抽、老抽,倒入可乐没过鸡翅', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/kl4.jpg' },
      { text: '大火烧开转小火炖20分钟,大火收汁即可', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/kl5.jpg' },
    ],
    notes: '可乐要选含糖的，无糖可乐做出来味道不够浓郁。收汁时要不停翻动，防止糊锅。'
  },
  {
    id: 20,
    name: '拔丝地瓜',
    description: '外脆里嫩，甜蜜拉丝的经典甜品',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/dg.jpg',
    time: '30分钟',
    servings: '3人份',
    difficulty: '中等',
    tags: ['甜品', '经典'],
    category: 'dessert',
    ingredients: ['地瓜2个', '白糖100克', '油适量'],
    steps: [
      { text: '地瓜去皮切块', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/dg1.jpg' },
      { text: '将地瓜加入淀粉，搅拌均匀', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/dg2.jpg' },
      { text: '锅中放油，炸地瓜至金黄', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/dg3.jpg' },
      { text: '锅中留少许油，加入白糖,小火炒至糖融化变成琥珀色,倒入地瓜快速翻炒均匀', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/dg4.jpg' },
    ],
    notes: '炒糖时火候要小，颜色变成琥珀色就可以倒入地瓜。动作要快，否则糖会变硬。'
  },
  {
    id: 21,
    name: '银耳莲子羹',
    description: '滋润养颜，口感爽滑的甜品',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/ye.jpg',
    time: '60分钟',
    servings: '4人份',
    difficulty: '简单',
    tags: ['甜品', '养颜'],
    category: 'dessert',
    ingredients: ['银耳1朵', '莲子50克', '红枣几颗', '枸杞适量', '冰糖适量'],
    steps: [
      { text: '干银耳15克，干白莲100克，冰糖80克', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/ye1.jpg' },
      { text: '将干银耳与莲子用清水泡发２小时，银耳拣去老蒂及杂质后撕成小朵，然后与泡过的莲子一起过水冲洗干净，滤干备用。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/ye2.jpg' },
      { text: '将银耳、莲子、冰糖倒入高压锅中，加入小半锅水，盖上盖，大火烧上汽后，改小火，炖30分钟左右。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/ye3.jpg' },
      { text: '最后开盖放气，热食或者晾凉后放入冰箱冷藏后再食用均可，冷食口感更佳。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/ye4.jpg' },

    ],
    notes: '银耳一定要充分泡发，撕得越碎越容易出胶。莲子芯一定要去掉，否则会苦。'
  },
  {
    id: 22,
    name: '蒸蛋糕',
    description: '松软可口，健康无油的家常蛋糕',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zdg5.jpg',
    time: '45分钟',
    servings: '4人份',
    difficulty: '中等',
    tags: ['甜品', '健康'],
    category: 'dessert',
    ingredients: ['鸡蛋3个', '细砂糖70克', '低筋面粉100克',],
    steps: [
      { text: '把4个鸡蛋打到一个无水无油的打蛋盆内，并滴上几滴白醋，打至粗泡加入糖并中速打发。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zdg1.jpg' },
      { text: '打发到出现清晰的纹路，蛋液从上面滴下来纹路不会马上消失就好了，这一歩很重要。我打了大约十一二分钟。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zdg2.jpg' },
      { text: '将拌好的蛋液倒入模具内，我用了四个4寸的南瓜模和一个4寸戚风模，又用了一个小饭碗，如果没有小模具用大的也行，吐司盒和大汤碗都行，都用小饭碗也行。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zdg3.jpg' },
      { text: '轻震，放入烧开水的锅里中火蒸十五分钟左右，这个跟具模具的大小调整时间。（上锅前可以盖上保鲜膜或碟子，我偷懒没有盖）', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zdg4.jpg' },
      { text: '蒸好后不要马上开锅盖，闷4～5分钟再开盖。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zdg5.jpg' },
      { text: '用枸杞更好看', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zdg6.jpg' },
    ],
    notes: '鸡蛋要打发到提起打蛋器能画出8字。翻拌时要轻柔，不要消泡。'
  },
  {
    id: 23,
    name: '凉拌黄瓜',
    description: '清爽开胃，简单快手的凉拌菜',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg4.jpg',
    time: '10分钟',
    servings: '2人份',
    difficulty: '简单',
    tags: ['素菜', '凉拌'],
    category: 'vegetable',
    ingredients: ['黄瓜1根', '大蒜3瓣', '香菜', '熟芝麻', '小米辣1个', '酱油2勺', '蚝油1勺', '盐半勺', '陈醋2勺'],
    steps: [
      { text: '黄瓜洗净拍碎切小块', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg1.jpg' },
      { text: '碗里放蒜末、小米辣、熟芝麻、1勺辣椒面，用一大勺热油浇', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg2.jpg' },
      { text: '加万能调味汁：2勺生抽+1勺蚝油+半勺盐+2勺陈醋+少许糖+少许香油', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg3.jpg' },
      { text: '以上调料加上香菜和花生米，拌拌拌，搞定！', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hg4.jpg' },

    ],
    notes: '黄瓜拍碎比刀切更入味。喜欢酸的可以多加醋，喜欢辣的多加辣椒油。'
  },
  {
    id: 24,
    name: '凉拌海带丝',
    description: '清爽开胃，营养丰富的凉拌菜',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hd5.jpg',
    time: '15分钟',
    servings: '2人份',
    difficulty: '简单',
    tags: ['素菜', '凉拌'],
    category: 'vegetable',
    ingredients: ['海带丝', '姜、蒜、盐', '油、味精', '生抽、陈醋（黑色）', '小米椒'],
    steps: [
      { text: '姜、蒜、小米椒（1：1：1）切碎备用。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hd1.jpg' },
      { text: '海带丝在水里煮10分钟左右，捞出过凉水备用。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hd2.jpg' },
      { text: '生抽、醋、盐、味精、白糖放在碗中，我这里是800克海带丝，用生抽、醋各三勺，盐、味精、白糖各2/3勺。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hd3.jpg' },
      { text: '把上步骤准备好的调料倒在海带里，姜、蒜也放在海带上面，热锅入油，油烧开以后，关火，放入小米椒炸香，把辣椒油倒在海带丝上。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hd4.jpg' },
      { text: '成品', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/hd5.jpg' },

    ],
    notes: '海带一定要焯熟，否则会硬。过冷水可以保持口感脆爽。'
  },
  {
    id: 25,
    name: '炒土豆丝',
    description: '酸辣脆爽，下饭神器的家常菜',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/td4.jpg',
    time: '20分钟',
    servings: '2人份',
    difficulty: '简单',
    tags: ['素菜', '下饭'],
    category: 'vegetable',
    ingredients: ['土豆2个', '香菜两根', '干辣椒:两个', '蒜末1大勺(约10g)', '五香粉(少许)', '酱油(10g)', '料酒(5g)', '醋(10g)', '糖(2g)', '盐(1小勺(约1g))'],
    steps: [
      { text: '准备两个土豆切成细丝', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/td1.jpg' },
      { text: '放入水中淘洗去除淀粉，水开放入锅中20-30秒钟即可捞出，捞出后过一遍凉水备用', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/td2.jpg' },
      { text: '葱蒜干辣椒倒入油锅中翻炒出味道', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/td3.jpg' },
      { text: '放入土豆丝，翻炒，加入盐生抽五香粉少许白糖翻炒均匀，出锅前来点锅边醋即可', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/td4.jpg' },

    ],
    notes: '土豆丝泡水可以去除淀粉，炒出来更脆。醋要最后放，这样醋香更浓。'
  },
  {
    id: 26,
    name: '青椒肉丝',
    description: '咸香可口，简单下饭的家常菜',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/rs8.jpg',
    time: '20分钟',
    servings: '2人份',
    difficulty: '简单',
    tags: ['肉类', '下饭'],
    category: 'meat',
    ingredients: ['猪肉丝200克', '青椒2个', '大蒜3瓣', '生抽5勺', '料酒1勺', '鸡精1勺', '蚝油1勺', '老抽1勺'],
    steps: [
      { text: '青椒洗干净切成丝状备用。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/rs1.jpg' },
      { text: '买来的肉切成丝状备用', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/rs2.jpg' },
      { text: '肉丝中加一勺盐、生抽两勺、老抽半勺后抓拌均匀，加入一勺淀粉后抓拌均匀，并用一勺食用油锁住水分。静待十分钟。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/rs3.jpg' },
      { text: '切点姜丝、葱丝和蒜末备用。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/rs4.jpg' },
      { text: '油热后加入肉丝，七成熟后盛入碗中备用，汤汁也一并盛入碗中', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/rs5.jpg' },
      { text: '起锅烧油，油热后放入切好的蒜末葱丝姜丝爆香，然后加入切好的青椒丝翻炒，加入一勺盐，炒至青椒丝断生。 ', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/rs6.jpg' },
      { text: '加入肉丝继续翻炒，同时加入一勺生抽、一勺鸡精、一勺蚝油。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/rs7.jpg'},
      { text: '继续翻炒均匀，一道美味下饭的青椒肉丝就做好啦！', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/rs8.jpg' }
    ],
    notes: '肉丝腌制后更嫩。青椒不要炒太久，保持脆嫩口感。'
  },
  {
    id: 27,
    name: '紫菜蛋花汤',
    description: '鲜美可口，简单快手的汤品',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zc4.jpg',
    time: '10分钟',
    servings: '2人份',
    difficulty: '简单',
    tags: ['汤羹', '快手'],
    category: 'soup',
    ingredients: ['紫菜1片', '鸡蛋1个', '葱花适量', '盐适量', '香油少许', '虾皮一把'],
    steps: [
      { text: '鸡蛋打散，葱切末，虾皮过水淘洗，紫菜一片备好。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zc1.jpg' },
      { text: '锅中倒水烧开，或直接倒入开水，放入虾皮和紫菜。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zc2.jpg' },
      { text: '倒入蛋液，勿搅拌，加少许盐', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zc3.jpg' },
      { text: '蛋液凝固后，稍搅拌，即可倒入盛葱花的碗中，放一勺香油即可。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/zc4.jpg' },

    ],
    notes: '蛋液要缓慢倒入，边倒边搅拌，蛋花才会均匀。紫菜煮太久会烂。'
  },
  {
    id: 28,
    name: '豆腐脑',
    description: '嫩滑可口，营养丰富的早餐',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/df7.jpg',
    time: '30分钟',
    servings: '4人份',
    difficulty: '中等',
    tags: ['汤羹', '早餐'],
    category: 'soup',
    ingredients: ['内脂豆腐1盒', '生抽1勺', '蚝油半勺', '胡椒粉少许', '老抽1勺', '盐2克', '淀粉2勺', '鸡蛋半个'],
    steps: [
      { text: '超市买的内脂豆腐一盒，倒入盘中开中火蒸10分钟。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/df.jpg' },
      { text: '现在准备卤汁：将提前泡好的木耳切丝。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/df.jpg' },
      { text: '木耳、老抽、生抽、蚝油、胡椒（或者你喜欢的其他调味品）放入锅中，加入一碗清水煮开。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/df.jpg' },
      { text: '加入淀粉水，勾芡。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/df.jpg' },
      { text: '加入蛋液，不要使劲搅，让蛋花略大一点。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/df.jpg' },
      { text: '蛋花入锅后再开锅就可以了。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/df.jpg' },
      { text: '豆腐用勺子挖成小块放入碗里，浇上卤汁就可以吃了。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/df.jpg' }
    ],

  },
  {
    id: 29,
    name: '酸奶水果沙拉',
    description: '清爽健康，色彩缤纷的甜品',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sg2.jpg',
    time: '15分钟',
    servings: '2人份',
    difficulty: '简单',
    tags: ['甜品', '健康'],
    category: 'dessert',
    ingredients: ['酸奶：130克左右(可多可少)', '香蕉：1根', '芒果：半个', '火龙果：半个', '圣女果：3个', '猕猴桃：1个'],
    steps: [
      { text: '五种水果切片、切丁装入盘中，然后把酸奶淋在盘中水果上即可。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sg1.jpg' },
      { text: '一道水果减肥沙拉就正式做好了！可以坐下来慢慢品味了！', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/sg2.jpg' },

    ],
    notes: '水果要新鲜，切好后尽快食用。可以根据喜好选择不同水果。'
  },
  {
    id: 30,
    name: '煎饺',
    description: '外酥里嫩，鲜香可口的传统美食',
    image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/jj6.jpg',
    time: '20分钟',
    servings: '3人份',
    difficulty: '中等',
    tags: ['经典', '主食'],
    category: 'meat',
    ingredients: ['饺子30个', '玉米淀粉	2平小勺（如果是餐馆瓷勺一勺即可）', '水（淀粉10倍量）	20平勺（餐馆白瓷勺的话只要10勺）', '芝麻 葱花	少许'],
    steps: [
      { text: '平底锅🍳少许油码入饺子🥟。小火煎出浅黄底（不要煎太过，不然后面会发黑）。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/jj1.jpg' },
      { text: '倒入调好的淀粉水（淀粉：水=1:10-12），越稀煎出的洞洞越大，但不要超过12。盖上盖继续中小火焖', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/jj2.jpg' },
      { text: '调蘸汁：醋+少许生抽和糖，喜欢蒜末的加一点。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/jj3.jpg' },
      { text: '检测边缘，哪里较湿润就挪到火最热处，直到整体边缘焦黄撒入葱花芝麻。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/jj4.jpg' },
      { text: '找合适直径的盘子盖上去，整体翻面扣出。', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/jj5.jpg' },
      { text: '有着漂亮冰花的煎饺就成功啦！', image: 'http://tos-ad-channel.whqycx.xyz/upload/ysqapp/jj6.jpg' },

    ],
    notes: '淀粉水的比例很重要，太浓会糊，太稀煎不出冰花。饺子要是熟饺子或半熟饺子。'
  }
]
module.exports = recipes